### ISSUE TITLE
WiVRn PC client GUI lobby panel z-fights with skybox in right eye

### ISSUE THREAD

**Issue by SpookySkeletons** [WiVRn/WiVRn#105]
Server and headset tested on is monado with the pimax WIP branch

**Comment by xytovl** [comment]
This might be caused by initial position of the panel, does it still happen after moving it? controller A button or hand palm pointing up to move it

**Comment by SpookySkeletons** [comment]
Yes I did move the lobby panel and it was still affected by this issue

**Comment by xytovl** [comment]
Considering the lobby panel is a quad layer and the skybox is a projection layer, this may be a monado bug.

Is it possible to provide a recording of the issue?

**Comment by xytovl** [comment]
closing as unable to reproduce
