### ISSUE TITLE
Lynx R1: Sleep mode borks WiVRn

### ISSUE THREAD

**Issue by SpookySkeletons** [WiVRn/WiVRn#110]
WiVRn unlike ALVR does not recover from sleep mode
Screen remains darkly lit, unable to interact with device
Must entirely reboot to escape

**Comment by damaestro** [comment]
This happens on the Focus 3 also.

**Comment by SpookySkeletons** [comment]
These two headsets share the same Qualcomm Spaces runtime. Attempts were made to logcat but sleepmode fills the log to rolling over with garbage on wake and the reason for wivrn blackscreen going undiscovered

**Comment by DanielKinsman** [comment]
Also on PICO. I think this is more of a feature request than a bug report, not sure it is implemented on any headset.

**Comment by damaestro** [comment]
At some point I was able to take the F3 off and the backlights would turn off. I could do some other things and then put the HMD back on and the session would still be active. I don't recall if it ever worked when the HMD went completely to sleep, but even just taking the HMD off now requires restarting the client on the F3.

**Comment by xytovl** [comment]
Should be fixed by 0133dd67cab92949cf7ac882681144112e84031a

**Comment by damaestro** [comment]
> Should be fixed by [0133dd6](https://github.com/WiVRn/WiVRn/commit/0133dd67cab92949cf7ac882681144112e84031a)

https://github.com/WiVRn/WiVRn-APK/releases/tag/apk-0133dd67cab92949cf7ac882681144112e84031a to test.

**Comment by SpookySkeletons** [comment]
It's a partial fix, the client is still highly likely to crash but not 100% stuck at black screen now.
Best case you sleep and unsleep out of a black screen or it until it works, or works first try
Worst case it crashes out of WiVRn client entirely and takes the handtrack with it.

**Comment by xytovl** [comment]
ea71191d5da455d9f91fa0578ddfbed39ebcc15f should fix the remaining case, can you check and close?

**Comment by SpookySkeletons** [comment]
All good, this is fully resolved, thankyou xy!
