### ISSUE TITLE
Encoder skips

### ISSUE THREAD

**Issue by SpookySkeletons** [WiVRn/WiVRn#111]
Many users including myself reporting the presence of
 WARN [comp_wivrn_present] Encoders not done with previous image, skip one
 In the logs indicating extremely bad performance and heavy encoding artifacts
 
 I am not able to readily reproduce this situation, seems random for now but it can be especially brutal.

**Comment by xytovl** [comment]
This should improved with Mesa 24.2 and cb644eea079ebad42993edb5a3358fa66d20f932 + 8c7491d4712c52bedc5aec32782b6f9b1e5cb96e
