### ISSUE TITLE
Lynx R1: Settings tab crashes WiVRn client

### ISSUE THREAD

**Issue by SpookySkeletons** [WiVRn/WiVRn#113]
I was informed this is due to the client code assuming facebook passthrough extension exists somewhere.

**Comment by xytovl** [comment]
Do you have any logs, stack trace?

There is no assumption on Facebook passthrough extension.

**Comment by SpookySkeletons** [comment]
Initially it was an unsupported https://registry.khronos.org/OpenXR/specs/1.1/man/html/xrEnumerateDisplayRefreshRatesFB.html ext causing the trouble

We must have a new extension causing trouble now.

**Comment by xytovl** [comment]
fixed by 9ef09256e8b29cb300e4a5370719352f855cc8c7
