### ISSUE TITLE
Unable to change controller interaction profile

### ISSUE THREAD

**Issue by JT8D-17** [WiVRn/WiVRn#114]
I want to change the interaction profile that is output by WiVRn for use in X-Plane 12, but I'm not having any luck.
By default, WiVRn reports controllers as Oculus, but I need them as Pico4 which I use and which may prove less problematic in X-Plane (judgement on that pending).

The OS is Arch Linux. I'm compiling WiVRn and the Android app myself from Git (not via Envision).

First, I edited wivrn_controller.cpp:

- Disabled all lines containing `WIVRN_CONTROLLER_THUMBREST_TOUCH` and the line `SET_INPUT(THUMBREST_TOUCH)`
- Replaced all instances of  `_TOUCH_` with `_PICO4_` and checked that results against Monado's controller list: https://monado.pages.freedesktop.org/monado/xrt__defines_8h.html

Then, I compiled WiVRn and the app, installed the latter, replaced X-Plane's OpenVR `libopenvr_api.so` with [https://gitlab.com/znixian/OpenOVR#linux-specific-info](opencomposite) and started X-Plane 12 with:

> export XR_RUNTIME_JSON="path/to/openxr_wivrn-dev.json"
> export XR_LOADER_DEBUG=all

&nbsp;

When monitoring terminal output, all I get for controllers is:

>[OC] UpdateInteractionProfile:920        /user/hand/left - Using interaction profile: /interaction_profiles/khr/simple_controller
[OC] UpdateInteractionProfile:920        /user/hand/right - Using interaction profile: /interaction_profiles/khr/simple_controller
[OC] CreateGenericTrackers:969   Checking for generic trackers...
[OC] CreateGenericTrackers:1019          Found 0 generic trackers
[OC] CreateGenericTrackers:1021          Creating generic trackers...
[OC] UpdateInteractionProfile:920        /user/hand/left - Using interaction profile: /interaction_profiles/khr/simple_controller
[OC] UpdateInteractionProfile:920        /user/hand/right - Using interaction profile: /interaction_profiles/khr/simple_controller

&nbsp;

The good thing: 
X-Plane appears to handle the simple controller properly, as its functionality corresponds to what the [https://gitlab.com/znixian/OpenOVR#linux-specific-info](OpenXR spec) states

The bad thing:
Well, it's not recognized as a Pico4 controller.

Is there anything else I can try?

(With no modification at all opencomposite correctly reports the Oculus Touch controller.)

**Comment by xytovl** [comment]
OpenComposite does not have any suggested bindings for pico4.

The changes you did in WiVRn replace the Oculus Touch binding with the Pico 4 one, but keeps the mapping for simple controller. This is why OpenComposite matches simple controller.

**Comment by SpookySkeletons** [comment]
Hopefully this can help you

This person is attempting to add Samsung Odyssey support to OpenComposite, which is what you will need to do for your Pico 4

https://gitlab.com/znixian/OpenOVR/-/merge_requests/128

**Comment by JT8D-17** [comment]
I've created an interaction profile for Pico4 in opencomposite (thanks for the link, @SpookySkeletons.) with all the data I could find and feeding it from my modified WiVRn server, but the controller is still picked up as "simple controller" by opencomposite.

Looking at "wivrn_controller.cpp", I just fail to figure out why WiVRn falls back to the simple controller if "_TOUCH_" is replaced by something else. All "_PICO4_" replacements I've made are supported by Monado.
I've also replaced "XRT_DEVICE_SIMPLE_CONTROLLER" with "XRT_DEVICE_PICO4_CONTROLLER" as a test and that does not produce any controller information in the opencomposite debug at all.

Is this still an issue on opencomposite's side or is there something else in WiVRn I must change?
Which source code files govern communication between WiVRn and opencomposite?

**Comment by xytovl** [comment]
If you want to continue on this, we may reopen the issue and label it as feature request.

You could then share the changes as branches in OpenComposite and WiVRn so that we have full visibility.

**Comment by JT8D-17** [comment]
I've created forks of WiVRn and opencomposite with my changes:

https://github.com/JT8D-17/WiVRn-Pico
https://github.com/JT8D-17/opencomposite

Not sure how exactly you people are doing this, but WiVRn's streaming quality is much better than ALVR's and that's why I want to try to get this going (primarily for X-Plane).

**Comment by xytovl** [comment]
On the OpenComposite side, you would need to either request OpenXR 1.1 or the XR_BD_controller_interaction extension.
You also have to add the Pico4InteractionProfile object in InteractionProfile::GetProfileList.

I think the WiVRn side is sufficient for a test.

**Comment by JT8D-17** [comment]
> On the OpenComposite side, you would need to either request OpenXR 1.1 or the XR_BD_controller_interaction extension. You also have to add the Pico4InteractionProfile object in InteractionProfile::GetProfileList.

Opencomposite uses OpenXR 1.0.12. After a bit of struggling, I managed to build it with 1.0.27 and `XR_BD_controller_interaction`.
Now I'm stumbling over unsupported legacy bindings in the Pico profile I've created. But at least this shows me that the profile is supposed to be used.

**Comment by JT8D-17** [comment]
`[OC] UpdateInteractionProfile:920        /user/hand/left - Using interaction profile: /interaction_profiles/bytedance/pico4_controller`

OH YEAH!

**Comment by JT8D-17** [comment]
So X-Plane correctly finds the controllers by name now.

However, I am stuck now as the WiVrn and opencomposite combo always puts me at a non-default position in X-Plane's VR menu, making it impossible to use it. There is also a weird rotation going on.
Resetting the play area on the headset, restarting the WiVRn client and WiVRn server prior to launching X-Plane has no effect. This is what it looks like:

[WiVRN_OC.webm](https://github.com/user-attachments/assets/c9ea8d31-25d9-403a-b248-6bb0a9cdb8d7)

For reference, SteamVR and ALVR works normally:

[SteamVR_ALVR.webm](https://github.com/user-attachments/assets/4c4a4c58-4667-4019-bcf3-1c16829604af)

Is this caused by WiVRn or Opencomposite?
