### ISSUE TITLE
Create an Issue Template for Bug Reporting

### ISSUE THREAD

**Issue by damaestro** [WiVRn/WiVRn#115]
We should create a github issue template for reporting bugs. https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

What all information should go into a bug report?

**Comment by Meumeu** [comment]
We should have at least the output of vulkaninfo, adb logcat, the server output and the content of config.json.

**Comment by damaestro** [comment]
build number from the APK's about tab
screenshot of the performance graph when the issue is happening
list of all setting values
from server (envision → hamburger menu → configure wivrn)
from client (app settings tab)
