### ISSUE TITLE
App crashes on launch Pico Neo 3

### ISSUE THREAD

**Issue by 7voxels221** [WiVRn/WiVRn#123]
Hello,

I am using a PICO Neo 3. When attempting to launch the app, it crashes on launch. I have attached the output of `adb logcat -s WiVRn` to the logfile below. Any help would be appreciated. Thanks.
[log-wivrn.txt](https://github.com/user-attachments/files/16919886/log-wivrn.txt)

**Comment by galister** [comment]
What's your Pico system version?

**Comment by 7voxels221** [comment]
My software version is 5.8.9.0

**Comment by xytovl** [comment]
It seems that Pico Neo 3 does not support Khronos OpenXR loader.

Documentation at https://developer.picoxr.com/document/native/openxr-sdk-quickstart/ states that it is supported, this is a Pico bug and should be reported to them.

**Comment by xytovl** [comment]
Closing as we don't plan to provide a Pico-specific loader, needs to be fixed on Pico firmware.
