### ISSUE TITLE
Mismatched sockets on Flatpak build

### ISSUE THREAD

**Issue by leaf-node** [WiVRn/WiVRn#124]
The Flatpak build is only working for me if I run:

```
ln -s wivrn/comp_ic /run/user/1000/wivrn_comp_ic
```

See:

* https://github.com/WiVRn/WiVRn/blob/master/flatpak/io.github.wivrn.wivrn.yml#L153
* https://github.com/WiVRn/WiVRn/blob/master/server/CMakeLists.txt#L51

It seemed to work before without that command, but I may have broken something by compiling and installing packages from source.

**Comment by xytovl** [comment]
The difference in socket path is intentional, as flatpak requires a directory to share the socket.

You may have a leftover file in `~/.config/openxr/1/active_runtime.json` that points to a non-flatpak wivrn.

**Comment by leaf-node** [comment]
Yes, that was it. Thanks! : )
