### ISSUE TITLE
Single-frame anomalies

### ISSUE THREAD

**Issue by galister** [WiVRn/WiVRn#130]
Every now and again, I see frames that don't belong. Likely a frame of an earlier timestamp.

Using 2 encoders (1 per vaapi device), this only happens in the left eye.

Seems to happen more often (once per 20-40s) while GPU load is high.

**Comment by xytovl** [comment]
This may be a problem on headset side if it does'nt have matching frames for left and right eyes.

Tweaking https://github.com/WiVRn/WiVRn/blob/a4edc0e1620ff403e23a570623441dcd1105eb92/client/scenes/stream.h#L60 to have more than 3 images to pick from may help.
https://github.com/WiVRn/WiVRn/blob/a4edc0e1620ff403e23a570623441dcd1105eb92/client/decoder/android/android_decoder.cpp#L98 will also need to be tweaked as ImageReader has a maximum number of available images (sum of what is stored in scene, one currently being decoded and one going from decoder to scene).

**Comment by galister** [comment]
after observing this more:
- with 1 encoder, there's obviously not an issue between the eyes, however it does seem that rarely there are frames that might be out of place
- with 3 encoders, there is very often visible tearing between the top and bottom part of the split eye. this is with top and bottom being in same encoder group.

**Comment by xytovl** [comment]
Could it be a synchronization issue with the `view_info` structure?

**Comment by xytovl** [comment]
Fixed by 9a39f2454113c28963d64aef9722837d9e89150d
