### ISSUE TITLE
A "Start a VR application" screen after following "Usage" steps

### ISSUE THREAD

**Issue by Hi-Angel** [WiVRn/WiVRn#131]
Idk if I'm doing something wrong as I'm new to VR, but as I'm just following the "Usage", I presume if I do, some amendments to README might be needed… So decided to create a report.

I have `Meta Quest 3`, am just trying to run Steam "Dagon" — a random free game featuring VR. Upon running the game Steam asks me if I want to run it as usual or in VR. I choose VR and the game menu appears, however WiVRn client inside headset keeps showing "Start a VR application" message as if nothing happened. I tried this game, and another one *(non-VR but Linux native)*, and running `Steam VR` alone, to no avail.

OpenComposite was installed. "Dagon" is being run via "Proton".

One thing that may or may not be relevant is README mentioning this:

> […] Files under `/usr` are mapped into `/run/host/usr` […]

This sounds as if some mount from `/usr` to `/run/host/usr` is expected to exist… But then mounts are a runtime thing and README mentions nothing about that. So in absence of clarity I didn't do anything here. I did provide the `VR_OVERRIDE` env. var to steam apps though as it's being explicitly asked by the WiVRn server.

# Steps to reproduce

1. Host: start `avahi-daemon` and `wivrn-server`
2. Headset: start `wivrn` app
3. Headset: chose connection to the host from the list. You should get a `Start a VR application` message.
4. Host: run Steam and put the following code to launch options of the Dagon and of Steam VR *(for good measure)*: `XR_RUNTIME_JSON=/run/host/usr/share/openxr/1/openxr_wivrn.json PRESSURE_VESSEL_FILESYSTEMS_RW=$XDG_RUNTIME_DIR/wivrn_comp_ipc %command%`
5. Run `Dagon` and in the popping up window chose `Launch Dagon in Steam VR Mode`, and wait for game menu to appear

## Expected

Game menu would appear on the headset

## Actual

Headset keeps showing a "Start a VR application" message

# Additional information

* OpenComposite version: git commit `f8db7aa3`
* WiVRn-server version: `0.18`
* WiVRn Android version: `0.18`
* WiVRn installation files list:

  <details>
      <summary>Details</summary>

  ```
  wivrn-server /usr/
  wivrn-server /usr/bin/
  wivrn-server /usr/bin/wivrn-server
  wivrn-server /usr/lib/
  wivrn-server /usr/lib/firewalld/
  wivrn-server /usr/lib/firewalld/services/
  wivrn-server /usr/lib/firewalld/services/wivrn.xml
  wivrn-server /usr/lib/systemd/
  wivrn-server /usr/lib/systemd/user/
  wivrn-server /usr/lib/systemd/user/wivrn-application.service
  wivrn-server /usr/lib/systemd/user/wivrn.service
  wivrn-server /usr/lib/wivrn/
  wivrn-server /usr/lib/wivrn/libmonado.so
  wivrn-server /usr/lib/wivrn/libmonado.so.0.0.0
  wivrn-server /usr/lib/wivrn/libmonado.so.24
  wivrn-server /usr/lib/wivrn/libopenxr_wivrn.so
  wivrn-server /usr/share/
  wivrn-server /usr/share/openxr/
  wivrn-server /usr/share/openxr/1/
  wivrn-server /usr/share/openxr/1/openxr_wivrn.json
  ```
  </details>
* WiVRn server logs after connecting headset and trying to run Dagon game and till I stopped it:

  <details>
      <summary>Details</summary>

  ```haskell
  λ wivrn-server
  WiVRn v0.18 starting
  For Steam games, set command to XR_RUNTIME_JSON=/run/host/usr/share/openxr/1/openxr_wivrn.json PRESSURE_VESSEL_FILESYSTEMS_RW=$XDG_RUNTIME_DIR/wivrn_comp_ipc %command%
  Removing stale socket file /run/user/1000/wivrn_comp_ipc
  Service published: dell-g15
  Server started, PID 349471
   INFO [ipc_server_main]  'v0.18' starting up...
  DEBUG [comp_main_create_system_compositor] Doing init 0x5744d6a5c1e0
   INFO [create_device] Created device and COMPUTE queue with QUEUE_GLOBAL_PRIORITY_MEDIUM.
   INFO [vk_print_device_info] Device info:
          name: Intel(R) UHD Graphics (CML GT2)
          vendor: 0x8086
          product: 0x9bc4
          deviceType: VK_PHYSICAL_DEVICE_TYPE_INTEGRATED_GPU
          apiVersion: 1.3.289
          driverVersion: 0x06002002
   INFO [vk_print_features_info] Features:
          timestamp_compute_and_graphics: true
          timestamp_period: 83.333336
          timestamp_valid_bits: 36
          timeline_semaphore: true
   INFO [vk_print_external_handles_info] Supported images:
          VK_EXTERNAL_MEMORY_HANDLE_TYPE_OPAQUE_FD_BIT:
                  color import=true export=true
                  depth import=true export=true
   INFO [vk_print_external_handles_info] Supported fences:
          VK_EXTERNAL_FENCE_HANDLE_TYPE_SYNC_FD_BIT: true
          VK_EXTERNAL_FENCE_HANDLE_TYPE_OPAQUE_FD_BIT: true
   INFO [vk_print_external_handles_info] Supported semaphores:
          VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(binary): true
          VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(binary): true
          VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_SYNC_FD_BIT(timeline): false
          VK_EXTERNAL_SEMAPHORE_HANDLE_TYPE_OPAQUE_FD_BIT(timeline): true
  [hevc_vaapi @ 0x5744d6c56100] Driver does not advertise encoder features, using guessed defaults.
  [hevc_vaapi @ 0x5744d6c56100] Driver does not advertise encoder block size, using guessed defaults.
   INFO [comp_vulkan_formats_log] Supported formats:
          VK_FORMAT_R16G16B16A16_UNORM: true
          VK_FORMAT_R16G16B16A16_SFLOAT: true
          VK_FORMAT_R16G16B16_UNORM: false
          VK_FORMAT_R16G16B16_SFLOAT: true
          VK_FORMAT_R8G8B8A8_SRGB: true
          VK_FORMAT_B8G8R8A8_SRGB: true
          VK_FORMAT_R8G8B8_SRGB: false
          VK_FORMAT_R8G8B8A8_UNORM: true
          VK_FORMAT_B8G8R8A8_UNORM: true
          VK_FORMAT_R8G8B8_UNORM: false
          VK_FORMAT_B8G8R8_UNORM: false
          VK_FORMAT_R5G6B5_UNORM_PACK16: true
          VK_FORMAT_R32_SFLOAT: true
          VK_FORMAT_D32_SFLOAT: true
          VK_FORMAT_D16_UNORM: true
          VK_FORMAT_X8_D24_UNORM_PACK32: true
          VK_FORMAT_D24_UNORM_S8_UINT: true
          VK_FORMAT_D32_SFLOAT_S8_UINT: true
          VK_FORMAT_S8_UINT: true
   WARN [u_linux_try_to_set_realtime_priority_on_thread] Could not raise priority for thread 'Multi Client Module'
   INFO [print_linux_end_user_started_information]
  ################################################################################
  #                                                                              #
  #                        The Monado service has started.                       #
  #                                                                              #
  ################################################################################
  ERROR [run] Exception in network thread: Socket shutdown
  Server exited, exit status 0
  Service published: dell-g15
  ^C
  ```
  </details>

**Comment by galister** [comment]
Add `PROTON_LOG=1 WINEDEBUG=vrclient,openxr,steam` to launch options. A `steam-xx.log` file will be created in your home folder where xx is the game ID.

If there are on messages with [OC] then it's likely trying to use SteamVR instead of OpenComposite. 

Note that not all games respect VR_OVERRIDE; for these titles to work, the only way I know is to edit `~/.config/openvr/openvrpaths.vrpath` directly. Note that Steam (not SteamVR) will try to actively change it back, so `chattr +i` on the .vrpath file might be a good idea.

**Comment by Hi-Angel** [comment]
> Add `PROTON_LOG=1 WINEDEBUG=vrclient,openxr,steam` to launch options. A `steam-xx.log` file will be created in your home folder where xx is the game ID.
> 
> If there are no messages with [OC] then it's likely trying to use SteamVR instead of OpenComposite.

Thank you, indeed there isn't a `OC` infix in the file. In case it matters, log file: [steam-1481400.log](https://github.com/user-attachments/files/17007880/steam-1481400.log).

> Note that not all games respect VR_OVERRIDE

I see, is there a free Steam VR game that is known to work, just so I could make sure the setup is correct?

>; for these titles to work, the only way I know is to edit `~/.config/openvr/openvrpaths.vrpath` directly. Note that Steam (not SteamVR) will try to actively change it back, so `chattr +i` on the .vrpath file might be a good idea.

Thank you, but I'm not clear what should I edit it to. The README mentions this file in the context of `/run/host` thing that as I mentioned in the 1st post is completely unclear. The `/run/host` directory doesn't exist if that matters. The current content of the file is this:

```json
{
        "config" : 
        [
                "/home/constantine/.local/share/Steam/config"
        ],
        "external_drivers" : null,
        "jsonid" : "vrpathreg",
        "log" : 
        [
                "/home/constantine/.local/share/Steam/logs"
        ],
        "runtime" : 
        [
                "/home/constantine/.local/share/Steam/steamapps/common/SteamVR"
        ],
        "version" : 1
}
```

**Comment by galister** [comment]
the runtime part must point to the parent folder of OpenComposite's `bin` folder.

(this bin folder)
```
bin
└── linux64
    └── vrclient.so
```

If you built OpenComposite from source, then this will be the `OpenComposite/build` folder.

Anything else can be left unchanged.

**Comment by Hi-Angel** [comment]
Thank you, okay, so, I feel there is definitely some confusion. First of all, I have `wivrn-server` installed and the package doesn't have a `vrclient.so` file, nor the `linux64` directory you mention. Here's the files list:

```
wivrn-server /usr/
wivrn-server /usr/bin/
wivrn-server /usr/bin/wivrn-server
wivrn-server /usr/lib/
wivrn-server /usr/lib/firewalld/
wivrn-server /usr/lib/firewalld/services/
wivrn-server /usr/lib/firewalld/services/wivrn.xml
wivrn-server /usr/lib/systemd/
wivrn-server /usr/lib/systemd/user/
wivrn-server /usr/lib/systemd/user/wivrn-application.service
wivrn-server /usr/lib/systemd/user/wivrn.service
wivrn-server /usr/lib/wivrn/
wivrn-server /usr/lib/wivrn/libmonado.so
wivrn-server /usr/lib/wivrn/libmonado.so.0.0.0
wivrn-server /usr/lib/wivrn/libmonado.so.24
wivrn-server /usr/lib/wivrn/libopenxr_wivrn.so
wivrn-server /usr/share/
wivrn-server /usr/share/openxr/
wivrn-server /usr/share/openxr/1/
wivrn-server /usr/share/openxr/1/openxr_wivrn.json
```

Additionally, I just realized that `wivrn-server` didn't mention `VR_OVERRIDE` variable among options to add to Steam, so I didn't have it set in the game "Launch options". But then again, I have no clue what should `VR_OVERRIDE` be set to, because README just says that it "also uses" `/run/host/usr`, which doesn't even exist in the first place. Should I literally pass a `VR_OVERRIDE=/run/host/usr`, or should I omit this variable since `wivrn-server` doesn't say anything about it?

**Comment by Hi-Angel** [comment]
I mean, I have set a `XR_RUNTIME_JSON`, I confused it with `VR_OVERRIDE`. The server itself mentions this among other variables to set. But this variable as well points to `/run/host/usr/share/openxr/1/openxr_wivrn.json` which "should be mapped" according to README, but it isn't and as I mentioned it's unclear if I should mount it or something…

**Comment by Hi-Angel** [comment]
I tried running the server under strace and grepping `/run/host`:

```bash
strace wivrn-server 2>&1 | grep /run/host
```

and the only match is from the write to stdout of the message about setting the env. variables. So FWIW `wivrn-server` doesn't even try to do anything with `/run/host`.

**Comment by galister** [comment]
I think I know what you got confused, so let me try and clear that up.

SteamVR workflow:
- Game loads `vrclient.so` as per `openvrpaths.vrpath`.
- This is SteamVR's `vrclient.so` and so it will try and connect to SteamVR.

WiVRn+OpenComposite workflow:
- Game loads `vrclient.so` as per `openvrpaths.vrpath`.
- This is `vrclient.so` is not from SteamVR, but it's actually OpenComposite.
- OpenComposite will check `XR_RUNTIME_JSON` to find the OpenXR loader, `libopenxr_wivrn.so`
- `libopenxr_monado.so` is loaded and connects to Monado via IPC.

For the WiVRn+OpenComposite setup, OpenComposite needs to be installed separately. Then the game must be told so use OpenComposite over SteamVR either via VR_OVERRIDE (depends on game) or the vrpaths file.

RE: `/run/host`, this is a folder specific to pressure-vessel, which is the container system used by Steam runtime. It only exists within the pressure vessel.

If this setup seems complicated, I recommend checking out [Envision](https://lvra.gitlab.io/docs/fossvr/envision/), which acts as a launcher and handles everything for you, including:
- WiVRn setup
- OpenComposite setup
- will not need to set `XR_RUNTIME_JSON` or `VR_OVERRIDE`, nor change any config files by hand

If you're going to try Envision, make sure to remove any `XR_RUNTIME_JSON` / `VR_OVERRIDE` from launch options of games.

**Comment by Hi-Angel** [comment]
Okay, thank you, it became somewhat clearer, although I still don't understand why I'm being told by `wivrn-server` to set `XR_RUNTIME_JSON` variable to a path to a json file under the "steam-only virtual filesystem `/run/host` *(specifically it says to set `XR_RUNTIME_JSON=/run/host/usr/share/openxr/1/openxr_wivrn.json`)*, but what I gather from your explanation it should be a path to either a `libopenxr_wivrn.so` file or to a subdirectory eventually leading to `libopenxr_wivrn.so`.

But it is 4 am here, so I think I better sleep it over 😊

> If this setup seems complicated

It isn't, it's just unclear. I'd be surprised if I was the first person to stumble upon this exact problem, I'd presume others just gave up. It would be beneficial for the community as a whole to figure out how it should work so it could be documented better.

**Comment by galister** [comment]
`/run/host/usr/share/openxr/1/openxr_wivrn.json` inside pressure-vessel maps to your real `/usr/share/openxr/1/openxr_wivrn.json`

and since the game runs inside pressure-vessel, the path needs to be set for how you'd see it from inside.

**Comment by galister** [comment]
You're not the first person, but most people who don't want to delve into the specifics just use Envision and forget about the fuss.

**Comment by clemens98** [comment]
> You're not the first person, but most people who don't want to delve into the specifics just use Envision and forget about the fuss.

correct keep coming back after a few months(to charge the vr related batteries to 80ish %)  and hope someone has a Linux vr solution that works 
alvr was a very good and easy to work with program sadly it did trow a container error no one could explain 
here its very hard to even know what you are supposed to do. and the console boxes that only pop up for a split second should be press enter to confirm instead

**Comment by Hi-Angel** [comment]
FTR, the last Monday I tried setting up per new information above but didn't succeed offhand, and afterwards I just didn't have time to get back to it. Hopefully I'll revisit it within a week, although would be amazing if someone could suggest a free Steam game that is known to work with VR, just so I could make sure the game is supposed to work and I only need to figure out the configuration.

**Comment by unknown321** [comment]
https://steamdb.info/app/611120/ is free and works although very laggy (proton issues?)
https://steamdb.info/app/579040/ works, but there is no "game" part

BeatSaber works without issues, Tetris Effect works but crashes after a while.

Check out OpenComposite compability list: https://docs.google.com/spreadsheets/d/1s2SSuRt0oHm91RUZB-R-ef5BrfOtvP_jwDwb6FuMF9Q/edit?gid=2068512515#gid=2068512515

I'm running WiVRn b6a668932 using `nvenc` and OpenOVR@f8db7aa358

Launch command: `VR_OVERRIDE=~/OpenOVR/build/ PRESSURE_VESSEL_FILESYSTEMS_RW=$XDG_RUNTIME_DIR/wivrn_comp_ipc %command%`

Debian 12, NVIDIA GeForce GTX 1080, 560.35.03.

**Comment by shayanz23** [comment]
Hey, Sorry to bother, but I'm having the same issue, and cannot get any game to stream to my headset when using wivrn without envision. I've tried everything, and I can't get it to work ever. I just tried the 0.20 version from flathub too, and it still had the same issue, the game starts, but nothing happens on the headset.

I did set the launch options for steam games and I still get nothing.

This is on ChachyOS (basically arch) and GNOME, but the same thing was happening on Arch with KDE.

I can't figure out what I'm doing wrong.

Interestingly, my [steam-620980.log](https://github.com/user-attachments/files/17427008/steam-620980.log) does have [OC] in it, so I think it is trying to connect to wivrn.

# GNOME System Details Report
---

## Report details
- **Date generated:**                              2024-10-17 18:47:06

## Hardware Information:
- **Hardware Model:**                              Micro-Star International Co., Ltd. MS-7D32
- **Memory:**                                      32.0 GiB
- **Processor:**                                   12th Gen Intel® Core™ i7-12700K × 20
- **Graphics:**                                    AMD Radeon™ RX 6700 XT
- **Disk Capacity:**                               5.5 TB

## Software Information:
- **Firmware Version:**                            H.A0
- **OS Name:**                                     CachyOS
- **OS Build:**                                    rolling
- **OS Type:**                                     64-bit
- **GNOME Version:**                               47
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.11.3-3-cachyos

**Comment by xytovl** [comment]
Your `/home/human/.config/openxr/1/active_runtime.json` file may be from a different runtime. Delete it and retry.

We plan to either add an information message prompting to do so or just overwrite the file on start for next release.

**Comment by shayanz23** [comment]
That worked! thank you!

**Comment by Hi-Angel** [comment]
> If this setup seems complicated, I recommend checking out Envision, which acts as a launcher and handles everything for you, including:

So, FYI, to end the weekend I tried to return back to this already multiple month long attempt to make WiVRn work. I updated both server and client to latest `0.21.1`, and tried following the README steps with "Defcon VR" that's supposed to work, but nothing of course worked. After some reading back and forth the discussion above and trying to figure all that out, I gave and decided to give a try to "Envision" which supposedly would handle everything for me.

Well, with Envision everything falls apart even earlier than with plain WiVRn:

![image](https://github.com/user-attachments/assets/b70b2b1c-dbeb-463f-a974-472ee417b69e)

it waits for me to connect WiVRn from Meta Quest 3 to computer, however the headset does not see the WiVRn that Envision is running *(it did see the plain WiVRn)*. Soo… 🤷‍♂️ Just hoping that in a few weeks when I get more spare time I'll be able to dig something out of it.

**Comment by Hi-Angel** [comment]
Okay, Envision connected after I rebooted headset

![image](https://github.com/user-attachments/assets/f9cddb5e-2c9e-449c-89a2-b6644d3171ba)

However, when I launch "Defcon VR", I get same "Start a VR application" screen 😄 So there's no difference, whether I'm running it from Envision or manually, it just doesn't work.

**Comment by Hi-Angel** [comment]
Okay, so for starters I did succeed starting up a native VR for of "the dark mod". [Here're installation instructions](https://github.com/fholger/thedarkmodvr/wiki/Installation) *(it's worth noting here that you need to chose specific version in the installer)*.

It's a good start, but I'm noticing that even with wifi shared directly from my laptop to MQ3 there's a noticeable lag in rendering *(e.g. when I turn, I see blackness for a second before it turns into textures)*. I presume it's due to network not being fast enough, but I don't think it's possible to improve any further *(it is a laptop ↔ MQ3 connection without a router, and devices are just in 60cm distance)*. So… is this expected behavior? Do people play games like that?
