### ISSUE TITLE
Support Vulkan Video encoder via ffmpeg?

### ISSUE THREAD

**Issue by leaf-node** [WiVRn/WiVRn#134]
Perhaps this will eventually allow older or less powerful graphics cards to quickly encode video with codecs used by WiVRn:

<https://www.phoronix.com/news/FFmpeg-Adds-Vulkan-Video-Encode>

**Comment by xytovl** [comment]
The plan is to use vulkan video encode directly, without ffmpeg, as we want more control over reference frames, synchronization and possibly other details.

Work has been started on https://github.com/WiVRn/WiVRn/tree/vulkan-video-encode

**Comment by xytovl** [comment]
Vulkan video support has been merged in master branch
