### ISSUE TITLE
Build failure on release 0.19

### ISSUE THREAD

**Issue by PassiveLemon** [WiVRn/WiVRn#135]
[wivrn.log](https://github.com/user-attachments/files/17065165/wivrn.log)

This is the Nix package derivation build log so formatting may be a little different, I'm not sure.

**Comment by xytovl** [comment]
This means patches in https://github.com/WiVRn/WiVRn/tree/master/patches/monado have not been applied

**Comment by PassiveLemon** [comment]
Oh I didn't notice that more patches were added. It builds now, thanks
