### ISSUE TITLE
Allow to manually specify IP Address

### ISSUE THREAD

**Issue by phil-flip** [WiVRn/WiVRn#144]
My Network doesn't allow ports between devices, or I sometimes use VR over a large distance. So I use Tailscale to connect my devices together. I used this on ALVR without any issues, but on WiVRn this doesn't work, because it prefers the local IP. When I try to use my mobile hotspot, it doesn't find it at all.
Is there any chance that we get a feature, to manually type in the IP, or it behaves like on ALVR?

**Comment by Meumeu** [comment]
It's been on the todo list for months, we still need to implement a virtual keyboard to be able to type the IP.

In the meantime, you can do it manually with `adb shell am start -a android.intent.action.VIEW -d wivrn://your-ip:9757 org.meumeu.wivrn.github` (or `org.meumeu.wivrn.local` if you compiled the APK yourself, or `org.meumeu.wivrn` if you installed it from the meta store)

**Comment by galister** [comment]
the client will remember the address, so this only needs to be done once

**Comment by phil-flip** [comment]
Thanks for the tip, tho I got it working. My IPv6 on the Desktop was off and the Network I'm on is a bit funky with ports on IPv4.
But I still would like to play over a larger distance, so I would like to keep this issue open.

**Comment by Meumeu** [comment]
Implemented in 0.21
