### ISSUE TITLE
Not detecting launched VR app

### ISSUE THREAD

**Issue by Masturbain** [WiVRn/WiVRn#155]
WiVRn (flatpak) doesn't detect when a VR app is launched and still ask to start an app.

Tried to give it all permissions via flatseal but doesn't change anything.
Only tried on steam games (beat saber, gorrila tag and openbrush) with and without arguments.
The argument WiVRn gave me : 

PRESSURE_VESSEL_FILESYSTEMS_RW=$XDG_RUNTIME_DIR/wivrn/comp_ipc:/var/lib/flatpak/app/io.github.wivrn.wivrn %command%

Distro : Zorin 
Headset : Quest 1

**Comment by Meumeu** [comment]
What's in `~/.config/openxr/1/active_runtime.json` when your headset is connected? If `library_path` does not point to `libopenxr_wivrn.so` you should delete `active_runtime.json` and reconnect.

**Comment by Masturbain** [comment]
I had installed it via apt. 
Since then i switched to Arch and it now works. 
Must be an issue with Zorin
