### ISSUE TITLE
Updated dependencies list, build instructions for Vulkan Video

### ISSUE THREAD

**Issue by leaf-node** [WiVRn/WiVRn#160]
Hi, now that Vulkan Video is supported, should the dependencies and build instructions be updated here: <https://github.com/WiVRn/WiVRn/blob/master/docs/building.md> and <https://github.com/WiVRn/WiVRn/>?

I ask for practical reasons, but also because I'm curious about whether FFmpeg is still a dependency, and how to build for Vulkan Video instead of FFmpeg.

Thanks! : )

**Comment by xytovl** [comment]
The vulkan backend is in addition to the ffmpeg/vaapi one.

I will update the build instructions, but there is no change in dependencies, except the required version of vulkan if you want video encode.

**Comment by leaf-node** [comment]
Is there a way to choose Vulkan Video over FFmpeg at compile time or run time?

**Comment by xytovl** [comment]
at runtime, in the configuration file, use "vulkan" instead of "vaapi" as the encoder
