### ISSUE TITLE
[feat] Support autostart within Flatpak sandbox

### ISSUE THREAD

**Issue by issacdowling** [WiVRn/WiVRn#171]
Though not something that most users would benefit from, I would find it useful if there was a way to ignore the Flatpak sandbox check when launching the autostart program (meaning it's no longer run using flatpak-spawn), allowing users to maintain tighter permissions on the WiVRn sandbox if they're willing to make their autostart program accessible from within it.

**Comment by xytovl** [comment]
Please check https://github.com/WiVRn/WiVRn/tree/feat/optional-flatpak-spawn

If the `talk` permission on `org.freedesktop.Flatpak` is not granted, spawning subprocesses will no longer use `flatpak-spawn --host`.

The provided autostart path must be visible inside the sandbox, at the configured location.
`adb` related features such as apk installing and USB mode will only work if `adb` is added in the flatpak, and appropriate permissions are set or an adb server is running outside of the sandbox

**Comment by issacdowling** [comment]
This works great, and seems like an excellent way to handle deciding whether to use flatpak-spawn or not, since it doesn't require the user to change any config options, and won't ever accidentally happen. Have got `wlx-overlay-s` going with this, and it's all good.

**Comment by xytovl** [comment]
implemented in 798374531778456011e4687284005c9fd72bbf44
