### ISSUE TITLE
WiVRn not launching

### ISSUE THREAD

**Issue by Seiko-Senpai** [WiVRn/WiVRn#189]
![image](https://github.com/user-attachments/assets/c48e6064-5743-47fc-8f1b-ebcc5daa7249)

So, fresh install of bazzite since nobara was having this same issue, and well yeah
image basically says it all
the titlebar is cutoff but it says opencomposite

installed through the discover app

sorry for the lack of detail, idk how to really explain it more than whats showed

**Comment by xytovl** [comment]
Could you provide additional information?

Running the server from commandline may show relevant details.
Adding `PROTON_LOG=1 WINEDEBUG=vrclient,openxr,steam` to the launch command will write a log file in your home folder, which may contain relevant information.

If you are using an NVIDIA GPU, you may be affected by https://github.com/WiVRn/WiVRn/issues/180

**Comment by Seiko-Senpai** [comment]
ill try
basically, add the command thats on the app to the launch params for vrchat, open in vr mode, for a split second in the headset i see something in the headset then it kicks me back to the menu and appears that issue on the game.
heres the log file
[steam-438100.log](https://github.com/user-attachments/files/17952444/steam-438100.log)

I am on an nvidia gpu yes

**Comment by Seiko-Senpai** [comment]
Ok so yeah, was just the issue you mentioned so ill close the issue now
