### ISSUE TITLE
Pico 4 - Client segfaults due to mem access violation 

### ISSUE THREAD

**Issue by Mhowser** [WiVRn/WiVRn#190]
It appears to be some kind of audio permission error, I can load into the client lobby and interact with wlx-overlay-s, but once i open a VR game it crashes. Tested with Resonite and Vrchat.

[28_11-15-39-02_564.log](https://github.com/user-attachments/files/17952939/28_11-15-39-02_564.log)
[28_11-15-47-59_146.log](https://github.com/user-attachments/files/17952940/28_11-15-47-59_146.log)

Client and server built from master branch and with Envision.

**Comment by xytovl** [comment]
Can you reproduce with a debug build ([apk-Standard-Debug](https://github.com/WiVRn/WiVRn/actions/runs/12064702765/artifacts/2248445279) from CI runs) and post the logs?

This should give more details on the crash.

**Comment by Mhowser** [comment]
Yes, I will report back once I get home today.

**Comment by Mhowser** [comment]
Here is the log from the debug build
[29_11-19-32-10_187.log](https://github.com/user-attachments/files/17964105/29_11-19-32-10_187.log)

**Comment by xytovl** [comment]
Unfortunately this does not provide the expected details (a readable stack trace pointing to the faulty code).

Can you try to narrow down the conditions that make it happen, as the trace mentions audio, you can try to start with microphone disable from client settings. You can also test running just a sound recorder on server when the headset is connected, but without launching a complete game.

**Comment by xytovl** [comment]
I tried to make audio code safer in https://github.com/WiVRn/WiVRn/tree/fix/audio-crash
Can you try the APK and see if it fixes the issue?

**Comment by Mhowser** [comment]
@xytovl do you have a preferred `adb` command to get a stack trace?

**Comment by xytovl** [comment]
You will have to run under a debugger to get anything, using Android Studio is almost the only choice to do so.

**Comment by xytovl** [comment]
On same branch https://github.com/WiVRn/WiVRn/tree/fix/audio-crash I added a workaround that removes the dynamic disabling of microphone for Pico 4.
This wastes resources if microphone is not being used but reverts to previous behaviour which should no longer crash.

If you can't find anything with a debugger, can you test the workaround?

**Comment by myghi63** [comment]
Now the app immediately crashes as soon as I connect to my PC. I'm trying to figure out how to compile and debug the APK on my pc to see if I'm able to find exactly what's going on.

**Comment by xytovl** [comment]
Fixed by 58115227a4b58419e48b74c980ce98ee6b522c96

The issue was encryption, as it is performed in-place, it was trying to write on the data from microphone, which is not allowed.
