### ISSUE TITLE
Forked Pipelines Fail to Build HMD Client

### ISSUE THREAD

**Issue by damaestro** [WiVRn/WiVRn#194]
Forks are unable to automatically build the APK due to requiring that there are tags in the repo.

The following needs to be made safe for this condition:

```
VERSION=$(git describe --tags)
```
https://github.com/WiVRn/WiVRn/blob/master/.github/workflows/Build.yml#L227

**Comment by xytovl** [comment]
Fixed by 003eee8e2f177e690695964e8d7590ad740cf3da
