### ISSUE TITLE
[Bug]: Desktop Entry Might Show up Twice

### ISSUE THREAD

**Issue by damaestro** [WiVRn/WiVRn#209]
### Describe the bug

More than one main category might cause the application to appear more than once

### Steps to Reproduce

desktop-file-validate io.github.wivrn.wivrn.desktop
hint: value "Network;Game" for key "Categories" in group "Desktop Entry" contains more than one main category; application might appear more than once in the application menu

### WiVRn Version

v0.22

### What GPU did the bug occur on?

NVIDIA

### What HMD did the bug occur on?

HTC Vive Focus 3

**Comment by damaestro** [comment]
I think you can set one Main Category and then as many additional that you want and the entry will only show up once.

**Comment by xytovl** [comment]
Fixed by dc4a00f2d546975c3b2f45f7dd15c187a1c62fe0
