### ISSUE TITLE
[Bug]: Connection to server dies on connect

### ISSUE THREAD

**Issue by ssmucny** [WiVRn/WiVRn#212]
### Describe the bug

When connecting to the server from the HMD the connection starts and then immediatly crashes

### Steps to Reproduce

1. Install Flatpak WiVRn
2. Register Quest 2
3. Attempt to connect to server

### Expected behavior

Connection stays connected

### WiVRn Version

0.22

## From Flatpak

```
flatpak run io.github.wivrn.wivrn 
Adding translator for  QLocale(English, Latin, United States)
Server started
Headset disconnected
Headset disconnected
adb devices exited with code 1 , status QProcess::NormalExit
stdout: ""
stderr: "Portal call failed: Failed to start command: Failed to execute child process “adb” (No such file or directory)\n"
Headset connected
Headset disconnected
adb devices exited with code 1 , status QProcess::NormalExit
stdout: ""
stderr: "Portal call failed: Failed to start command: Failed to execute child process “adb” (No such file or directory)\n"
adb devices exited with code 1 , status QProcess::NormalExit
```

## System Logs

The core dump occurs when attempting to connect

```

Dec 13 21:09:39 flatpak[304782]: adb devices exited with code 1 , status QProcess::NormalExit
Dec 13 21:09:39 flatpak[304782]: stdout: ""
Dec 13 21:09:39 flatpak[304782]: stderr: "Portal call failed: Failed to start command: Failed to execute child process “adb” (No such file or directory)\n"
Dec 13 21:09:39 flatpak[304782]: adb devices exited with code 1 , status QProcess::NormalExit
Dec 13 21:09:39 flatpak[304782]: stdout: ""
Dec 13 21:09:39 flatpak[304782]: stderr: "Portal call failed: Failed to start command: Failed to execute child process “adb” (No such file or directory)\n"
Dec 13 21:09:40 flatpak[304782]: adb devices exited with code 1 , status QProcess::NormalExit
Dec 13 21:09:40 flatpak[304782]: stdout: ""
Dec 13 21:09:40 flatpak[304782]: stderr: "Portal call failed: Failed to start command: Failed to execute child process “adb” (No such file or directory)\n"
Dec 13 21:09:40 audit[305062]: ANOM_ABEND auid=1000 uid=1000 gid=1000 ses=3 subj=unconfined_u:unconfined_r:spc_t:s0 pid=305062 comm="wivrn-server" exe=2F7661722F686F6D652F73736D75636E792F2E6C6F63616C2F73686172652F656E766973696F6E2F70726566697865732F776976726E5F64656661756C742F62696E2F776976726E2D736572766572202864656C6574656429 sig=7 res=1
Dec 13 21:09:40 kernel: traps: wivrn-server[305062] trap stack segment ip:55d74e8d9083 sp:7ffd2ae5cfc0 error:0 in wivrn-server[df083,55d74e817000+1ba000]
Dec 13 21:09:40 systemd-coredump[305063]: Process 305062 (wivrn-server) of user 1000 terminated abnormally with signal 7/BUS, processing...
Dec 13 21:09:40 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=drkonqi-coredump-processor@16-305063-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 13 21:09:40 systemd-coredump[305064]: [🡕] Process 305062 (wivrn-server) of user 1000 dumped core.
                                          
                                          Stack trace of thread 305062:
                                          #0  0x000055d74e8d9083 n/a (/var/home/ssmucny/.local/share/envision/prefixes/wivrn_default/bin/wivrn-server (deleted) + 0xdf083)
                                          ELF object binary architecture: AMD x86-64
Dec 13 21:09:40 systemd[1]: systemd-coredump@16-305063-0.service: Deactivated successfully.
Dec 13 21:09:40 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=systemd-coredump@16-305063-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 13 21:09:40 systemd[1698]: Started drkonqi-coredump-launcher@214-305065-0.service - Launch DrKonqi for a systemd-coredump crash (PID 305065/UID 0).
Dec 13 21:09:40 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=drkonqi-coredump-processor@16-305063-0 comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Dec 13 21:09:40 systemd[1]: drkonqi-coredump-processor@16-305063-0.service: Deactivated successfully.
Dec 13 21:09:40 systemd[1]: drkonqi-coredump-processor@16-305063-0.service: Consumed 78ms CPU time, 68.5M memory peak.
Dec 13 21:09:40 drkonqi-coredump-launcher[305074]: Unable to find file for pid 305062 expected at "kcrash-metadata/wivrn-server.563ffeeef55146f79c5d53cc56637715.305062.ini"
Dec 13 21:09:40 drkonqi-coredump-launcher[305074]: Nothing handled the dump :O

```

### What GPU did the bug occur on?

AMD

### Vulkan Info

Vulkan Instance Version: 1.3.296

Instance Extensions: count = 24
-------------------------------
VK_EXT_acquire_drm_display             : extension revision 1
VK_EXT_acquire_xlib_display            : extension revision 1
VK_EXT_debug_report                    : extension revision 10
VK_EXT_debug_utils                     : extension revision 2
VK_EXT_direct_mode_display             : extension revision 1
VK_EXT_display_surface_counter         : extension revision 1
VK_EXT_headless_surface                : extension revision 1
VK_EXT_surface_maintenance1            : extension revision 1
VK_EXT_swapchain_colorspace            : extension revision 4
VK_KHR_device_group_creation           : extension revision 1
VK_KHR_display                         : extension revision 23
VK_KHR_external_fence_capabilities     : extension revision 1
VK_KHR_external_memory_capabilities    : extension revision 1
VK_KHR_external_semaphore_capabilities : extension revision 1
VK_KHR_get_display_properties2         : extension revision 1
VK_KHR_get_physical_device_properties2 : extension revision 2
VK_KHR_get_surface_capabilities2       : extension revision 1
VK_KHR_portability_enumeration         : extension revision 1
VK_KHR_surface                         : extension revision 25
VK_KHR_surface_protected_capabilities  : extension revision 1
VK_KHR_wayland_surface                 : extension revision 6
VK_KHR_xcb_surface                     : extension revision 6
VK_KHR_xlib_surface                    : extension revision 6
VK_LUNARG_direct_driver_loading        : extension revision 1

Instance Layers: count = 5
--------------------------
VK_LAYER_MESA_device_select       Linux device selection layer 1.3.211  version 1
VK_LAYER_VALVE_steam_fossilize_32 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_fossilize_64 Steam Pipeline Caching Layer 1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_32   Steam Overlay Layer          1.3.207  version 1
VK_LAYER_VALVE_steam_overlay_64   Steam Overlay Layer          1.3.207  version 1

Devices:
========
GPU0:
        apiVersion         = 1.3.289
        driverVersion      = 24.2.7
        vendorID           = 0x1002
        deviceID           = 0x744c
        deviceType         = PHYSICAL_DEVICE_TYPE_DISCRETE_GPU
        deviceName         = AMD Radeon RX 7900 XTX (RADV NAVI31)
        driverID           = DRIVER_ID_MESA_RADV
        driverName         = radv
        driverInfo         = Mesa 24.2.7
        conformanceVersion = 1.3.0.0
        deviceUUID         = 00000000-2d00-0000-0000-000000000000
        driverUUID         = 414d442d-4d45-5341-2d44-525600000000
GPU1:
        apiVersion         = 1.3.289
        driverVersion      = 0.0.1
        vendorID           = 0x10005
        deviceID           = 0x0000
        deviceType         = PHYSICAL_DEVICE_TYPE_CPU
        deviceName         = llvmpipe (LLVM 19.1.0, 256 bits)
        driverID           = DRIVER_ID_MESA_LLVMPIPE
        driverName         = llvmpipe
        driverInfo         = Mesa 24.2.7 (LLVM 19.1.0)
        conformanceVersion = 1.3.1.1
        deviceUUID         = 6d657361-3234-2e32-2e37-000000000000
        driverUUID         = 6c6c766d-7069-7065-5555-494400000000

### What HMD did the bug occur on?

Quest 2

### ADB Logs

N/A?

**Comment by xytovl** [comment]
The only crash visible in logs is related to an envision-installed server.
I would expect flatpak logs to contain the text "WiVRn v0.22 starting".

Can you make sure wivrn-server is started from the flatpak and not an external tool. Also please describe what is displayed on the headset app when this happens.

**Comment by ssmucny** [comment]
I reinstalled the app on the quest and it is working now. It may have been trying to connect to the wivrn instance that I configured in a testing container (an external tool) instead of the flatpak. Deleting/recreating the connection probably fixed it, but I'm not sure exactly why. I'm closing the issue since I can't reproduce this anymore.
