### ISSUE TITLE
WiVRn hasnt updated to glslang 15 and is broken on arch.

### ISSUE THREAD

**Issue by space2ninja101** [WiVRn/WiVRn#219]
/run/media/space/games/SteamVR/bin/wivrn-server: error while loading shared libraries: libglslang.so.14: cannot open shared object file: No such file or directory
WiVRn exited with code 127

**Comment by space2ninja101** [comment]
I am currently on glslang 15.0.0-2

**Comment by space2ninja101** [comment]
downgrading also requires so.15?

**Comment by space2ninja101** [comment]
using LD_LIBRARY_PATH set to a folder of the required libraries does not work but for other applications it does. what is going on here??

**Comment by galister** [comment]
have you tried just rebuilding it?

**Comment by space2ninja101** [comment]
> have you tried rebuilding wivrn?

yes multiple times

**Comment by space2ninja101** [comment]
never mind this was an issue with my dependencies. closing
