### ISSUE TITLE
[Feature request] SteamVR support

### ISSUE THREAD

**Issue by LuNeder** [WiVRn/WiVRn#86]
Hiii

I think it'd be cool to have the ability to use SteamVR with WiVRn, since SteamVR got a lot better recently. Reasons that come to my mind for this being useful are:

- SteamVR gives you a cool and complete UI on the headset side, which is cool since it lets you launch games and talk to friends without having to remove the headset or having to use wlx-overlay for that. It's a more seamless UX I guess. If I'm being honest, this is probably my biggest reason to think that having steamvr would be cool :3.
- Some games don't seem to like opencomposite, either having distorted views or even just crashing. 
- Quest 3 has some weird black bars in some games (not sure if that'd be fixed just by using steamvr on wivrn tho).

Monado seems to have a plugin for that, but I was not able to get it to work with WiVRn at all so I guess it's not supported

Love WiVRn btw :D 

(I apologize for bothering y'all if this is not a planned feature \^-\^)

**Comment by iijj22gg** [comment]
+1 to this

This might turn WiVRn into interesting alternative to ALVR

**Comment by damaestro** [comment]
For the time being, you can use [OpenComposite](https://gitlab.com/znixian/OpenOVR) in combination with WiVRn to play openvr based games without steamvr. Not everything plays, but for right now this is the best bet.

[Envision](https://gitlab.com/gabmus/envision) will build OpenComposite for you and dynamically patch the steam container if the local environment supports it.

**Comment by srwxr-xr-x** [comment]
+1 to this, it would be awesome
