### ISSUE TITLE
Into The Radius 2: Unplayable Due to Position Offset

### ISSUE THREAD

**Issue by Riebeck-one** [WiVRn/WiVRn#96]
Starting Into The Radius 2 (which I believe natively runs on OpenXR) results in the game being displayed correctly in the HMD, but with such a significant position offset that it is unplayable most of the time, as I can be hundreds of meters away from the main menu. Each time I restart the game, my position changes, and if I'm lucky enough, I can spawn close enough to the game menu to select "start playing." However, even after that, there is a loading screen, and when I'm actually in the game, the huge position offset occurs once again, causing me to spawn outside of the map.

I tried other games like Phasmophobia (an OpenXR game) and Half-Life: Alyx (with Open Composite), and I did not encounter such issues.

Additionally, running the game through ALVR does not result in such a position offset.

Hardware:
- Oculus Quest 3
- AMD 7900XTX on PC

Software:
- Arch Linux with Mesa 24.1.4
- KDE Plasma 6 Wayland compositor
- Envision 0.1.0 starting WiVRn 0.17
- WiVRn 0.17 on Quest 3

**Comment by xytovl** [comment]
It seems origin was not initialized correctly, can you verify that https://github.com/Meumeu/WiVRn/tree/fix/tracking-origin-init fixes the issue?

**Comment by Riebeck-one** [comment]
I just tried this fix, and it didn't change anything unfortunately. However, I discovered something interesting. If I run the game without wearing the headset, wait until I get to the main menu, and then put on the headset, my position in the game is correct. I tried this several times, and it seems perfectly consistent. Unfortunately, I still can't play since I have to wear the headset to load my save, and after loading, I'm still off the map.

**Comment by xytovl** [comment]
I noticed there was an error in the recentering function, and published a client fix on the same branch.

Can you test with an apk from CI https://github.com/Meumeu/WiVRn/actions/workflows/Build.yml?query=branch%3Afix%2Ftracking-origin-init

This should fix recentering (long press on menu button), and may change the initial position too.

**Comment by Riebeck-one** [comment]
I recompiled the fix/tracking-origin-init branch and installed the APK from this link: https://github.com/Meumeu/WiVRn/actions/runs/10180260880, but the issue persists. It seems that recentering only adjusts the rotation and not the position.

**Comment by xytovl** [comment]
We don't log relevant information for this.

If you have some development skills, it would be interesting to know:
* The absolute pose sent by the client, received at https://github.com/Meumeu/WiVRn/blob/360a3c5fe6d29ca83c5f09ff499b83623ef8d2e2/server/driver/wivrn_hmd.cpp#L264
* The pose as seen by the OpenXR application
* The stage/local offset in https://github.com/Meumeu/WiVRn/blob/1d4124ee90b397a0592b353a24e6ac3d459343a9/client/scenes/stream.cpp#L982

**Comment by Riebeck-one** [comment]
I don't have those skills, unfortunately. I think I'll just wait for someone with more experience and the same problem to help you.

Thanks for trying to help me.

**Comment by Riebeck-one** [comment]
Here are the server log :
[WiVRn_Server_log.txt](https://github.com/user-attachments/files/16455439/WiVRn_Server_log.txt)
And the client log:
```
adb logcat -e  "local offset"
--------- beginning of main
08-01 13:24:50.881  7425  7503 I WiVRn   : [2024-08-01 13:24:50.881] [WiVRn] [info] stage/local offset: 0, -1.3374841, 0
```

**Comment by xytovl** [comment]
According to those logs, the position reported by WiVRn is about 1m from origin.
How far were you from the menu in the game?

**Comment by xytovl** [comment]
I mean, the logs you posted give a distance of around 1m and I need to know if this matches the distance in the game.

Can you check again what position is reported in logs (server logs should be sufficent) when distance is large in-game.

**Comment by Riebeck-one** [comment]
Okay, I just tried several times by only restarting the game without restarting the WiVRn connections. The first time, I couldn't see where I was; the second time, I was right in front of the menu as it is supposed to be; and the third time, I was about 30 meters away from it, as you can see in this screenshot:
![image](https://github.com/user-attachments/assets/8df4d834-df63-4bf7-b9f2-195b1f86e1ce)

There is only these lines of log for the client:

`adb logcat -e  "local offset"
--------- beginning of main
08-01 15:14:30.793  5815  5894 I WiVRn   : [2024-08-01 15:14:30.793] [WiVRn] [info] stage/local offset: 0, -1.2091378, 0
`
And this is the log for the server from the three times I ran the game:
[WiVRn_log.txt](https://github.com/user-attachments/files/16457085/WiVRn_log.txt)

From what I can see, the position in the game does not seem to be related to what the log returns.

**Comment by Riebeck-one** [comment]
Okay, so I found a way to consistently play the game, even though it's not sustainable in the long run. All I have to do is put my quest to sleep anytime there is a loading screen and turn it back on when the loading is done. This way, I spawn correctly in the game.
When I do this, there is a sudden change in the head position returned by the server.
It goes from something like :
` INFO [update_tracking] head position: 0.023796,1.263465,0.007255`
To something like :
` INFO [update_tracking] head position: 4.546057,-1.212925,1.258573`
instantly

**Comment by Riebeck-one** [comment]
I tested again since there was an update for both Wivrn and the game itself, and this issue seems to be resolved.
